# Configuration file for i18n-check validation.
# See https://github.com/activist-org/i18n-check for details.

src-dir: frontend
i18n-dir: frontend/i18n
i18n-src: frontend/i18n/en-US.json

file-types-to-check: [.ts, .vue]

checks:
  # Global configurations are applied to all checks.
  global:
    active: True
    directories-to-skip: [frontend/node_modules, frontend/.nuxt]
    files-to-skip: []
  missing-keys:
    active: False
