# Configuration file for i18n-check validation.
# See https://github.com/activist-org/i18n-check for details.

src-dir: frontend/app
i18n-dir: frontend/Scribe-i18n/i18n/locales
i18n-src: frontend/Scribe-i18n/i18n/locales/en-US.json

file-types-to-check: [.ts, .vue]

checks:
  # Global configurations are applied to all checks.
  global:
    active: True
  missing-keys:
    active: False
  key-naming:
    keys-to-ignore: [i18n.app.*]
