// SPDX-License-Identifier: AGPL-3.0-or-later
export enum IconMap {
  APPLE = "simple-icons:apple",
  ARROW_DOWN = "bi:arrow-down",
  ARROW_LEFT = "bi:arrow-left",
  ARROW_RIGHT = "bi:arrow-right",
  ARROW_UP = "bi:arrow-up",
  CIRCLE_INFO = "bi:info-circle",
  COLOR_MODE_DARK = "bi:moon",
  COLOR_MODE_LIGHT = "bi:sun",
  COLOR_MODE_SYSTEM = "bi:circle-half",
  ENVELOPE = "bi:envelope",
  EXTERNAL_LINK = "bi:box-arrow-up-right",
  F_DROID = "simple-icons:fdroid",
  FORK = "octicon:repo-forked-24",
  GITHUB = "simple-icons:github",
  GLOBE = "bi:globe",
  GOOGLE_PLAY = "simple-icons:googleplay",
  HEART = "bi:heart-fill",
  MASTODON = "simple-icons:mastodon",
  MATRIX = "IconMatrix",
  SHARE = "bi:box-arrow-up",
}
