<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
<template>
  <div class="overflow-hidden bg-layer-0">
    <Head>
      <Title>{{ $t("i18n.pages.index.title") }}</Title>
    </Head>
    <LandingSplash />
    <LandingCommunityBanner />
    <div
      class="mb-2 mt-4 flex flex-col sm:mb-4 sm:mt-10 xl:mb-8 xl:mt-16 2xl:mb-12 2xl:mt-24"
    >
      <LandingContent
        contentPosition="left"
        header="i18n.pages.index.language_keyboards_header"
        tagline="i18n.pages.index.language_keyboards_tagline"
        text="i18n.pages.index.language_keyboards_text"
        :imgUrl="LANGUAGE_KEYBOARDS_IMAGE_URL"
        imageAltText="i18n.pages.index.language_keyboards_img_alt_text"
        btnText1="i18n.pages.index.learn_more"
        btnUrl1="/"
        btnAriaLabel1="i18n.pages.index.language_keyboards_aria_label"
        btnId1="btn-language-keyboards"
      />
      <LandingContent
        contentPosition="right"
        header="i18n.pages.index.conjugate_header"
        tagline="i18n.pages.index.conjugate_tagline"
        text="i18n.pages.index.conjugate_text"
        :imgUrl="CONJUGATE_IMAGE_URL"
        imageAltText="i18n.pages.index.conjugate_img_alt_text"
        btnText1="i18n.pages.index.learn_more"
        btnUrl1="/"
        btnAriaLabel1="i18n.pages.index.conjugate_aria_label"
        btnId1="btn-conjugate"
      />
      <LandingContent
        contentPosition="left"
        header="i18n.pages.index.infrastructure_header"
        tagline="i18n.pages.index.infrastructure_tagline"
        text="i18n.pages.index.infrastructure_text"
        :imgUrl="INFRASTRUCTURE_IMAGE_URL"
        imageAltText="i18n.pages.index.infrastructure_img_alt_text"
        btnText1="i18n.pages.index.learn_more"
        btnUrl1="/"
        btnAriaLabel1="i18n.pages.index.infrastructure_aria_label"
        btnId1="btn-infrastructure"
      />
      <LandingTechBanner />
      <LandingContent
        contentPosition="right"
        header="i18n.pages.index.about_us"
        tagline="i18n.pages.index.scribe_section_tagline"
        text="i18n.pages.index.scribe_section_text"
        :imgUrl="SCRIBE_ICON_IMAGE_URL"
        imageAltText="i18n._global.scribe_icon_img_alt_text"
        btnText1="i18n.pages.index.learn_more"
        btnUrl1="/"
        btnAriaLabel1="i18n.pages.index.scribe_section_btn_aria_label"
        btnId1="btn-scribe"
      />
      <LandingContent
        contentPosition="top"
        header="i18n.pages.index.our_supporters"
        tagline="i18n.pages.index.our_supporters_tagline"
        text="i18n.pages.index.our_supporters_text"
        imageAltText=""
        btnText1="i18n.pages.index.become_supporter"
        btnUrl1="/"
        btnAriaLabel1="i18n.pages.index.our_supporters_btn_become_aria_label"
        btnText2="i18n.pages.index.view_all_supporters"
        btnUrl2="/"
        btnAriaLabel2="i18n.pages.index.our_supporters_btn_view_aria_label"
        subText=""
        btnId1="btn-become-supporter"
        btnId2="btn-our-supporters"
      />
    </div>
  </div>
</template>
